# Generated by Django 3.1.5 on 2022-01-26 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=200)),
                ('team_captain', models.CharField(max_length=200)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
